# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PollfishMoPubAdapter' do
  use_frameworks!

  pod 'Pollfish', '<6.0.0'
  pod 'mopub-ios-sdk'
end
